# BASIC PYTHON

1.Split the string

In [1]:
s="Hi there Sam!"
print(s.split())

['Hi', 'there', 'Sam!']


2.Use.format() to print the following string

Output should be:The diameter of Earth is 12742 kilometers

In [2]:
print("The diameter of {planet} is {diameter} kilometers.".format(planet='Earth',diameter='12742'))

The diameter of Earth is 12742 kilometers.


In the Nest dictionary grab the word "hello"

In [3]:
dict = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(dict['k1'][3]['tricky'][3]['target'][3])

hello


NUMPY

4.1 Create an array of 10 Zeros?
4.2 Create an array of 10 fives?

In [19]:
import numpy as np

In [6]:
#4.1
array=np.zeros(10)
print("An array of 10 Zeros : ",array)

An array of 10 Zeros :  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [10]:
#4.2
array=np.ones(10)*5
print("An array of 10 Fives : ",array)

An array of 10 Fives :  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


5.Create an array of all the even intergers from 20 to 35?

In [13]:
array=np.arange(20,36,2)
print("An array of all the even intergers from 20 to 35 :",array)

An array of all the even intergers from 20 to 35 : [20 22 24 26 28 30 32 34]


6.Create a 3x3 matrix with values ranging from 0 to 8?

In [15]:
matrix=np.arange(0,9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7.Concatenate a and b
a=np.array([1,2,3]) , b=np.array([4,5,6])

In [23]:
a=np.array([1,2,3]) 
b=np.array([4,5,6])
print(np.concatenate((a,b)))


[1 2 3 4 5 6]


8.Create a dataframe with 3 rows and 2 columns

In [24]:
import pandas as pd


In [28]:
r=[1,2,3]
c=['a','b']
data=np.random.randint(10,size=(3,2))
df=pd.DataFrame(data,index=r,columns=c)
print(df)

   a  b
1  5  3
2  8  5
3  0  9


9.Generate the series of dates from 1st Jan 2023 to 10th Feb 2023

In [29]:
pd.date_range(start="2023-01-01",end="2023-02-10")

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10', '2023-01-11', '2023-01-12',
               '2023-01-13', '2023-01-14', '2023-01-15', '2023-01-16',
               '2023-01-17', '2023-01-18', '2023-01-19', '2023-01-20',
               '2023-01-21', '2023-01-22', '2023-01-23', '2023-01-24',
               '2023-01-25', '2023-01-26', '2023-01-27', '2023-01-28',
               '2023-01-29', '2023-01-30', '2023-01-31', '2023-02-01',
               '2023-02-02', '2023-02-03', '2023-02-04', '2023-02-05',
               '2023-02-06', '2023-02-07', '2023-02-08', '2023-02-09',
               '2023-02-10'],
              dtype='datetime64[ns]', freq='D')

10.Create 2D list to DataFrame?

In [30]:
lists = [[1,'aaa', 22], [2,'bbb', 25], [3,'ccc', 24]] 
df = pd.DataFrame(lists, columns =['Token', 'ID','value']) 
print(df )

   Token   ID  value
0      1  aaa     22
1      2  bbb     25
2      3  ccc     24
